### ISSUE TITLE
Detect custom directory

### ISSUE THREAD

**Issue by lokesh-krishna** [jmbuhr/telescope-zotero.nvim#1]
Would it be possible to detect the custom directory set in Zotero and if not then to pass it as an option?

 I tried using the plugin with `~/.local/share/zotero` set as the custom directory in Zotero and the plugin still looks in `~/Zotero/`.

**Comment by jmbuhr** [comment]
This is not a directory, but the path to the database file. What did you set `zotero_db_path = '~/Zotero/zotero.sqlite` to?

**Comment by jmbuhr** [comment]
For example, if I add
```lua
        config = function()
          require('zotero').setup {
            zotero_db_path = 'test',
          }
          vim.keymap.set('n', '<leader>fz', ':Telescope zotero<cr>', { desc = '[z]otero' })
```
to my config, I get the expected error and an empty picker.
![image](https://github.com/jmbuhr/telescope-zotero.nvim/assets/17450586/20b6eb85-bb64-4df4-8508-237e01015622)

**Comment by lokesh-krishna** [comment]
I didn't notice the option to specify the db_paths and am very embarrassed.
