### ISSUE TITLE
Letting users optionally specify .bib file 

### ISSUE THREAD

**Issue by danieleavitabile** [jmbuhr/telescope-zotero.nvim#5]
I've seen from your Lua code that the .bib file is inferred. Maybe a possible change would be to let the user specify a bib file other than the one crudely fetched from the plugin? This may be useful when interfacing, for instance, with a .tex file

**Comment by jmbuhr** [comment]
I just added the feature, but I don't write much plain tex these days, so let me know if the formatting works for you.

**Comment by danieleavitabile** [comment]
I got some time to test it now. Following your configuration instructions

1. the address for your plugin should be 'jmbuhr/telescope-zotero.nvim', or the plugin would not install on my computer
2. my linter and compiler exit with an error because the module bib is not defined so bib.locate_tex_bib does not work as expected

**Comment by jmbuhr** [comment]
What linter and compiler?

**Comment by danieleavitabile** [comment]
The standard lua that ship with Neovim: when. I configure the package as you write in the instructions I get an error at startup from Neovim, that the bib module is not found. Separately from that, I have standard LSP configured for lua, and while I edit the file as you write in the instruction, the linter tries to tell me that indeed bib is not defined.



Daniele Avitabile
Associate Professor in Applied Mathematics
www.danieleavitabile.com


On 23 March 2024 at 11:45:34, Jannik Buhr ***@***.******@***.***>) wrote:

What linter and compiler?

**Comment by jmbuhr** [comment]
yeah, these are the defaults, so if you want to use the defaults you just leave them out, not copy them. But I can make the example also work as is, one sec.

**Comment by jmbuhr** [comment]
I corrected the readme and opts code

**Comment by danieleavitabile** [comment]
To me it still exits with an error, as it can not find zotero.bib

**Comment by jmbuhr** [comment]
Does the latest change clarify it: https://github.com/jmbuhr/telescope-zotero.nvim?tab=readme-ov-file#setup?
